[tool.black]
target-version = ['py37']
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
)/
'''

[tool.tox]
legacy_tox_ini = '''
[tox]
envlist = style

[testenv:style]
deps =
	pre-commit
commands = pre-commit run --all-files
'''
